channels:
  - pytorch
  - pyg
  - gurobi
  - nvidia
  - defaults
dependencies:
  - python=3.9.15
  - numpy=1.21.5
  - pytorch=1.13.0
  - pytorch-cuda=11.6
  - pytorch-lightning=1.7.7
  - pyg=2.2.0
  - networkx=2.8.4
  - gurobi=10.0.0
  - yaml=0.2.5