ppo:
    gamma: 0.99
    lam: 0.95
    lr: 0.005
    lr_gamma: 0.995
    batch_size: 64
    steps_per_epoch: 1024
    nb_optim_iters: 4
    clip_ratio: 0.1
    clip_decay: 0.998
    ent_weight: 0.01
    critic_weight: 0.5
    gradient_clip_val: 1
    model_params:
        fac_c_in: 7
        c_hidden: 128
        c_out: 128
        num_layers: 3
        layer_name: GraphConv
        edge_dim: 1
        heads: 1
    data_path: ./data/train_100_1000/

ppo_trainer:
    max_epochs: 300
    accelerator: gpu
    devices: [1]
    auto_select_gpus: False
    track_grad_norm: 2
